### ISSUE TITLE
Replace legacy API map visualization

### ISSUE THREAD

**Issue by Frangible** [Safecast/safecastapi#197]
## Todos:

- [x] Put the BVM init in a function and call that from the _map partial so we don't do that work on every page load
- [x] Switch up binds per [nick's comment](https://github.com/Safecast/safecastapi/pull/362#issuecomment-297747324)
- [x] See about adding a scale to the page using [this sprite](https://github.com/Safecast/Tilemap/blob/master/scales64_fullcolor_240x854.png)

## Original description

The current API legacy map visualization has the following issues:
1. The markers have poor visibility against the basemaps.
2. The markers are not z-indexed nor decuttered, making it difficult for mods to see anomalies.
3. The server often fails to generate the marker .js data for large drives, timing out.

A solution to this has already been developed, and merely requires being plugged in:
1. The bGeigie Log Viewer, a component of the [Tilemap](https://github.com/Safecast/Tilemap).
2. Fully client side, no other deps.  Resolves all client issues, is faster, requires no server resources.

**Changes required:**  
1. Existing map:  
   - On the API server, there is a job or process that generates marker data from logfiles for the legacy map.  This can be disabled/removed when the page code is migrated.  
   - On the legacy map HTML page, whatever current JS or includes are being used should be obviously removed.
   - On the legacy map HTML page, the layout should be changed to remove the static information pane from the left side of the screen.  
2. New map:  
   - Including the necessary .js files for the bGgeigie Log Viewer and its worker.  
3. Invoking:  
   - Instanting the main controller class and invoking the function to load a log file.  

**Requirements:**  
- **Files:** [bgeigie_viewer.js](https://github.com/Safecast/Tilemap/blob/master/bgeigie_viewer.js) and [bgeigie_viewer_worker.js](https://github.com/Safecast/Tilemap/blob/master/bgeigie_viewer_worker.js)
- **Library Dependencies:** None, except Google Maps API v3
- **Repo:** [Safecast Tilemap](https://github.com/Safecast/Tilemap) which also contains a conceptual overview.

**After including the .js files:**
1. **EITHER** a) No File Transfer UI:
   - The databind object passed to the controller class must be modified such that the databind for the UI is set to NULL. 
   - `binds.elementIds.bv_transferBar` should be set to NULL to prevent showing the file transfer progress UI.  
   - This is the simplest approach and should require no other configuration. _(untested)_  
2. **OR** b) File Transfer UI.  
   - If the transfer UI is desired, the default databinds can be used, but there are additional requirements as follows:
   - `<div id="bv_transferBar" class="bv_transferBarHidden"></div>` must be added to the HTML document as a static databind element.
   - [world_155a_z0.png](https://github.com/Safecast/Tilemap/blob/master/world_155a_z0.png) must be in the same path as the .js files.
   - [bgeigie_viewer_inline.css](https://github.com/Safecast/Tilemap/blob/master/bgeigie_viewer_inline.css) must be previously loaded or copy/pasted into the HTML.
   - All of this is documented at the top of `bgeigie_viewer.js`
3. Instantiate and retain an instance of BVM, the main controller class.  
   - `var bvm = new BVM(map, databinds);`
4. Invoke `GetLogFileDirectFromUrlAsync` to load and display a log file.
   - `bvm.GetLogFileDirectFromUrlAsync("https://safecast-production.s3.amazonaws.com/uploads/bgeigie_import/source/12070/100-1111.LOG", 12070);`

**Comment by matschaffer** [comment]
As a point of comparison:

http://safecast.org/tilemap/?y=56.1528&x=10.171&z=14&l=11&m=4&logids=14490 -- 7.3s
https://api.safecast.org/en-US/bgeigie_imports/14490 -- 32s+ (often doesn't finish)

Since most of the work happens against the s3 drive data, this should also take pressure off API since that 32s figure is largely spend building JSON.

<img width="1201" alt="transactions_-_safecastapi_-_new_relic" src="https://cloud.githubusercontent.com/assets/690/9816034/43e850f0-58d5-11e5-94fe-944fb768438e.png">

**Comment by matschaffer** [comment]
@Frangible just tried loading http://safecast.org/tilemap/?y=56.1528&x=10.171&z=14&l=11&m=4&logids=14490 and not seeing anything. Everything alright with the tilemap log viewer?

**Comment by matschaffer** [comment]
Another great case:
- http://api.safecast.org/en-US/bgeigie_imports/26302 ~22s of SQL madness
- http://safecast.org/tilemap/?y=37.3992&x=140.3749&z=15&l=11&m=4&logids=26302 such speed, much wow

**Comment by matschaffer** [comment]
Another sample for integration from nick: http://safecast.org/tilemap/test2/bgeigie_viewer_demo.html

**Comment by Frangible** [comment]
> @Frangible just tried loading http://safecast.org/tilemap/?y=56.1528&x=10.171&z=14&l=11&m=4&logids=14490 and not seeing anything. Everything alright with the tilemap log viewer?

@matschaffer - Sorry, missed this earlier.  Can't replicate.  Maybe a random timeout during load?  If you can replicate, please include your JS console.

> Another sample for integration from nick: 
> http://safecast.org/tilemap/test2/bgeigie_viewer_demo.html

It's two lines of code!

```
Integrating bgeigie_viewer.js      Dark Souls                 Learning Japanese
|                                  |                                 |
|----|----|----|----|----|----|----|----|----|----| [POWER GAP] |----|
|                           MORE DIFFICULT --->
+-- You are here.
```

**Comment by matschaffer** [comment]
I have some initial work here going locally, just need to integrate the latest updates from https://github.com/Safecast/Tilemap and set up some tags in the html to load the actual log file for the page you're on.

![screen shot 2017-04-25 at 21 42 29](https://cloud.githubusercontent.com/assets/690/25465203/cdfb128e-2b3b-11e7-956c-4aebdb4a7a2e.png)

**Comment by nokton** [comment]
Hi Mat - that’s great!!

Pieter

**Comment by nokton** [comment]
Haha!

Can’t wait for these two lines, Nick!

Pieter

**Comment by nokton** [comment]
One request from many volunteers has been the display of the legend on the page - hope we can make that wish come true this time ;-)

**Comment by matschaffer** [comment]
Up on staging now - page render time is *much* better:

```
❯ time curl -s https://api.safecast.org/en-US/bgeigie_imports/14490 >/dev/null
curl -s https://api.safecast.org/en-US/bgeigie_imports/14490 > /dev/null  0.02s user 0.01s system 0% cpu 11.333 total

❯ time curl -s http://api-staging.safecast.org/en-US/bgeigie_imports/14490 >/dev/null
curl -s http://api-staging.safecast.org/en-US/bgeigie_imports/14490 >   0.00s user 0.00s system 0% cpu 0.895 total
```

**Comment by matschaffer** [comment]
@Frangible just re-iterating from slack. If you know of a good way to hide the legend and add a "loading..." until the map is ready that'd be nice I think.

Otherwise we're probably good to go here.

Note when testing that staging has a very old DB so not all prod URLs will also be available on staging.

**Comment by matschaffer** [comment]
Still a few things to sort out, but merged and deployed the PR for now. Will open a new ticket for the stragglers.
