### ISSUE TITLE
Ingest pipelining

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#356]
## Status

Made some great headway on this during the week of Sept 4. We now have SNS & SQS in place for both dev & prod. And some somewhat-duct-tapey workers publishing to s3 and elastic search.

Elasticsearch connection info is:

~dev:~ (shut down to avoid wasting resources)
~es: https://2515c8ed2c1d881fdbde7d8c960c902e.us-west-2.aws.found.io:9243~
~kb: https://2e8c1c9fc59aa9bc6267871ebc45d3ca.us-west-2.aws.found.io:9243~

prd:
es: https://40ad140d461d810ac41ed710b5c7a5b6.us-west-2.aws.found.io:9243
kb: https://03a7d5abd1d836ffe2772e95abc7dd25.us-west-2.aws.found.io:9243

Contact me on slack for a login.

## TODOs

- [x] switch elastic cloud worker to service
- [x] change bucket policy so s3 batch exports can be read publicly
- [x] switch bulk worker to cron job
- [ ] set up https://github.com/elastic/curator to ensure we only keep 30-90 days of hot data in the ES cluster
- [ ] set up an oauth proxy so anyone with github access can get into kibana (maybe another ticket)
- [ ] set up a s3 batch process that writes parquet files that work with AWS Athena (maybe another ticket)

## Background

Ideally we want ingest to feed multiple consumers. 

The ones we know we need today are:
- postgres append log (measurements jsonb table)
- normalized postgis table (for easier/faster tile generation queries)
- s3 (for cold storage, emr+hive or athena)

I'd be curious to add:
- elasticsearch
- prometheus + grafana (good time series exploration & alerting)

Ray also found:
- [axibase](https://github.com/axibase/atsd-docs/blob/master/tutorials/getting-started.md) with [chartlab](https://apps.axibase.com/chartlab/dee79515#fullscreen) - even has a [ruby api](https://github.com/axibase/atsd-api-ruby) for pushing data

This is my basic idea for how to structure it. Note that the queue consumers could be a common pool of boxes, or maybe even and ECS cluster.

![cloudcraft - solarcast ingest](https://cloud.githubusercontent.com/assets/690/22957090/6d4f3794-f369-11e6-9f4e-5f58168ad119.png)

**Comment by matschaffer** [comment]
In doing some more research it looks like we can probably have ingest publish to SNS, then have SNS do fan out to multiple SQS queues. Or possibly straight to http endpoints for data stores that don't need to batch/buffer.

Will need to prototype to be sure.

Kinesis is also an option for this, but it looks expensive for just 5 messages per second.

Kafka also looks interesting but there's heavy operational load there (not hosted, zookeeper is also required).

I suspect kinesis or kafka will make more sense in a future where we have 50+ SNS topics or a project that can benefit from in-order delivery.

**Comment by matschaffer** [comment]
Elastic Cloud on AWS just went live, so looking forward to trying that as a pipeline sink https://aws.amazon.com/marketplace/pp/B01N6YCISK

**Comment by matschaffer** [comment]
Just keeping a note that looks like I may be able to talk to Kay & Morten at Elastic about a sponsored elastic cloud cluster as well. Not sure on all the details yet.

**Comment by matschaffer** [comment]
Came across https://github.com/atlassian/localstack which may be useful for testing

**Comment by matschaffer** [comment]
http://www.timescale.com/ Is another contender for a write location

**Comment by matschaffer** [comment]
Had to restart ES worker today after this:
```
D, [2017-10-05T20:34:14.376510 #5461] DEBUG -- Workers::ElasticCloud: Message version was 1
2017-10-05 20:34:14 +0000: POST https://ingest:********@40ad140d461d810ac41ed710b5c7a5b6.us-west-2.aws.found.io:9243/ingest-measurements-2017-10-05/measurement [status:400, request:0.020s, query:N/A]
2017-10-05 20:34:14 +0000: > {"device":101,"when_captured":"2017-10-05T20:34:13Z","loc_lat":37.4932,"loc_lon":139.93304,"loc_olc":"8Q9XFWVM+76F","lnd_7318u":41,"service_uploaded":"2017-10-05T20:34:14Z","service_transport":"ngeigie:107.161.164.166","service_md5":"7d6388a49696f3c054c4ae5db16fe5dc","service_handler":"i-051a2a353509414f0","@timestamp":"2017-10-05T20:34:14Z","ingest":{"location":{"lat":37.4932,"lon":139.93304}}}
2017-10-05 20:34:14 +0000: < Illegal request
2017-10-05 20:34:14 +0000: [400] Illegal request
E, [2017-10-05T20:34:14.397310 #5461] ERROR -- Workers::ElasticCloud: Unable to save measurement: [400] Illegal request
rake aborted!
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] Illegal request
/var/app/current/app/workers/elastic_cloud.rb:48:in `block in run'
/var/app/current/app/workers/elastic_cloud.rb:25:in `run'
/var/app/current/Rakefile:46:in `block (2 levels) in <top (required)>'
Tasks: TOP => workers:elastic_cloud
(See full trace by running task with --trace)
```

I restarted the worker and things seem to be running. Not sure why we'd get transient 400s but we should make sure to catch/retry when we do. Maybe add logging to show how ES responded as well.

**Comment by matschaffer** [comment]
Closing this out as it's working and TODO items should be picked up in other github issues.
